### ISSUE TITLE
it don't work on linux

### ISSUE THREAD

**Issue by vt92i** [bootloopmaster636/ugd_timer#29]
maybe because timezone differentce. i am using utc+0. i don't know.
![image](https://github.com/bootloopmaster636/ugd_timer/assets/48002426/46aeb990-dcb1-461d-afdb-2962a56beca3)

**Comment by bootloopmaster636** [comment]
should work despite locale difference... it's because the code on autostart forgot to start the timer when autostart disabled

**Comment by bootloopmaster636** [comment]
fixed in #30

**Comment by bootloopmaster636** [comment]
should work now... thanks for reporting the issue
